version: "3.3"

services:
  mongo:
    image: mongo
    restart: always # Changes reset
    container_name: mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always # Changes reset
    container_name: mongoGui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      # - ./mysql_data:/var/lib/mysql
      - ./mongo_data:/data/db
